from abc import ABC, abstractmethod
from typing import Dict, Any, List
from pathlib import Path

class BasePlugin(ABC):
    """
    Abstract Base Class for all Amanu Output Plugins.
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Plugin name (e.g., 'markdown', 'pdf')."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Brief description of what the plugin does."""
        pass

    @property
    @abstractmethod
    def default_extension(self) -> str:
        """Default file extension for artifacts generated by this plugin (e.g., 'md', 'pdf')."""
        pass

    @abstractmethod
    def generate(self, context: Dict[str, Any], template_content: str, output_path: Path, raw_transcript: List[Dict[str, Any]] | None = None, **kwargs) -> Path:
        """
        Generate an artifact.
        
        Args:
            context: The enriched context data (from Refine stage).
            template_content: The raw content of the selected template.
            output_path: The full path where the file should be saved.
            raw_transcript: Optional. The raw transcription segments (from Scribe stage).
            **kwargs: Additional arguments.
            
        Returns:
            Path to the generated file.
        """
        pass
